# Generated by Django 3.0.5 on 2020-06-22 19:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='document',
            field=models.ImageField(null=True, upload_to=account.models.upload_location),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to=account.models.upload_location),
        ),
    ]
