# Generated by Django 3.0.5 on 2020-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200622_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_code',
            field=models.CharField(default='123456', max_length=6),
        ),
        migrations.AddField(
            model_name='account',
            name='verified_at',
            field=models.DateTimeField(null=True, verbose_name='verified at'),
        ),
    ]
