# Generated by Django 3.0.5 on 2020-09-17 08:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200704_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='document',
            field=models.FileField(null=True, upload_to=account.models.file_upload_location),
        ),
    ]
