# Generated by Django 3.0.5 on 2020-09-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_image_reviewer'),
        ('post', '0002_remove_post_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='place.Place'),
        ),
    ]
