# Generated by Django 3.0.5 on 2020-07-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20200714_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='user_id',
            new_name='user',
        ),
    ]
