# Generated by Django 3.0.5 on 2020-09-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20200714_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
    ]
