# Generated by Django 3.0.5 on 2020-09-16 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0005_image_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
